FROM golang:1.19-alpine

WORKDIR /usr/app

COPY ./go.mod .
COPY ./go.sum .

# RUN go get . 

# CMD ["go","run","."]
RUN apk add --update tzdata \
    git;
RUN go install github.com/pilu/fresh@latest

CMD ["fresh"]