version: '3.9'
services:
    db:
        image: 'postgres'
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    server:
        restart: always
        build:
            context: .
            dockerfile: './Dockerfile.dev'
        ports:
            - '8000:8000'
        volumes:
            - '.:/usr/app'
